[build]
command = "npm run build:netlify"
functions = ".netlify/functions"
publish = ".netlify/output/public"

[build.environment]
NODE_VERSION = "22"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/"
[headers.values]
Cache-Control = "public, max-age=3600, must-revalidate"
