[build]
command = "bun run build"
functions = ".output/server"
publish = ".output/public"
node_version = "22.0.0"

[[headers]]
for = "/dist/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/"
[headers.values]
Cache-Control = "public, max-age=3600, must-revalidate"
